version: '3'

services:
  tweet_collector:
    build: TweepyContainer/
    volumes:
      - ./TweepyContainer/:/TweepyContainer
    depends_on:
      - my_mongodb

  airflow:
    build: airflow/
    volumes:
      - ./airflow/dags/:/usr/local/airflow/dags/
      - ./airflow/requirements.txt:/usr/local/airflow/requirements.txt
    ports:
      - "8081:8080"
    command: ["webserver", "scheduler"]
    depends_on:
      - my_mongodb
      - my_postgresdb

  my_mongodb:
    image: mongo
    ports:
      - 27017:27017

  my_postgresdb:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=xxxx
    ports:
      - 5555:5432

  slacky:
    build: slackyContainer/
